% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Inference for numerical data},
  pdfauthor={Emmanuel Kasigazi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Inference for numerical data}
\author{Emmanuel Kasigazi}
\date{}

\begin{document}
\maketitle

\subsection{Getting Started}\label{getting-started}

\subsubsection{Load packages}\label{load-packages}

In this lab, we will explore and visualize the data using the
\textbf{tidyverse} suite of packages, and perform statistical inference
using \textbf{infer}. The data can be found in the companion package for
OpenIntro resources, \textbf{openintro}.

Let's load the packages.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(openintro)}
\FunctionTok{library}\NormalTok{(infer)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(tinytex)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\subsubsection{The data}\label{the-data}

Every two years, the Centers for Disease Control and Prevention conduct
the Youth Risk Behavior Surveillance System (YRBSS) survey, where it
takes data from high schoolers (9th through 12th grade), to analyze
health patterns. You will work with a selected group of variables from a
random sample of observations during one of the years the YRBSS was
conducted.

Load the \texttt{yrbss} data set into your workspace.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(}\StringTok{\textquotesingle{}yrbss\textquotesingle{}}\NormalTok{, }\AttributeTok{package=}\StringTok{\textquotesingle{}openintro\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

There are observations on 13 different variables, some categorical and
some numerical. The meaning of each variable can be found by bringing up
the help file:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{?yrbss}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What are the cases in this data set? How many cases are there in our
  sample?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(yrbss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tibble [13,583 x 13] (S3: tbl_df/tbl/data.frame)
##  $ age                     : int [1:13583] 14 14 15 15 15 15 15 14 15 15 ...
##  $ gender                  : chr [1:13583] "female" "female" "female" "female" ...
##  $ grade                   : chr [1:13583] "9" "9" "9" "9" ...
##  $ hispanic                : chr [1:13583] "not" "not" "hispanic" "not" ...
##  $ race                    : chr [1:13583] "Black or African American" "Black or African American" "Native Hawaiian or Other Pacific Islander" "Black or African American" ...
##  $ height                  : num [1:13583] NA NA 1.73 1.6 1.5 1.57 1.65 1.88 1.75 1.37 ...
##  $ weight                  : num [1:13583] NA NA 84.4 55.8 46.7 ...
##  $ helmet_12m              : chr [1:13583] "never" "never" "never" "never" ...
##  $ text_while_driving_30d  : chr [1:13583] "0" NA "30" "0" ...
##  $ physically_active_7d    : int [1:13583] 4 2 7 0 2 1 4 4 5 0 ...
##  $ hours_tv_per_school_day : chr [1:13583] "5+" "5+" "5+" "2" ...
##  $ strength_training_7d    : int [1:13583] 0 0 0 0 1 0 2 0 3 0 ...
##  $ school_night_hours_sleep: chr [1:13583] "8" "6" "<5" "6" ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(yrbss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age           gender             grade             hispanic        
##  Min.   :12.00   Length:13583       Length:13583       Length:13583      
##  1st Qu.:15.00   Class :character   Class :character   Class :character  
##  Median :16.00   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :16.16                                                           
##  3rd Qu.:17.00                                                           
##  Max.   :18.00                                                           
##  NA's   :77                                                              
##      race               height          weight        helmet_12m       
##  Length:13583       Min.   :1.270   Min.   : 29.94   Length:13583      
##  Class :character   1st Qu.:1.600   1st Qu.: 56.25   Class :character  
##  Mode  :character   Median :1.680   Median : 64.41   Mode  :character  
##                     Mean   :1.691   Mean   : 67.91                     
##                     3rd Qu.:1.780   3rd Qu.: 76.20                     
##                     Max.   :2.110   Max.   :180.99                     
##                     NA's   :1004    NA's   :1004                       
##  text_while_driving_30d physically_active_7d hours_tv_per_school_day
##  Length:13583           Min.   :0.000        Length:13583           
##  Class :character       1st Qu.:2.000        Class :character       
##  Mode  :character       Median :4.000        Mode  :character       
##                         Mean   :3.903                               
##                         3rd Qu.:7.000                               
##                         Max.   :7.000                               
##                         NA's   :273                                 
##  strength_training_7d school_night_hours_sleep
##  Min.   :0.00         Length:13583            
##  1st Qu.:0.00         Class :character        
##  Median :3.00         Mode  :character        
##  Mean   :2.95                                 
##  3rd Qu.:5.00                                 
##  Max.   :7.00                                 
##  NA's   :1176
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check the number of cases (observations) in the dataset}
\NormalTok{num\_cases }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(yrbss)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Number of cases in the YRBSS dataset:"}\NormalTok{, num\_cases))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Number of cases in the YRBSS dataset: 13583"
\end{verbatim}

\textbf{``Number of cases in the YRBSS dataset: 13583''}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Look at the dimensions of the dataset}
\NormalTok{dim\_info }\OtherTok{\textless{}{-}} \FunctionTok{dim}\NormalTok{(yrbss)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Dimensions:"}\NormalTok{, dim\_info[}\DecValTok{1}\NormalTok{], }\StringTok{"rows by"}\NormalTok{, dim\_info[}\DecValTok{2}\NormalTok{], }\StringTok{"columns"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Dimensions: 13583 rows by 13 columns"
\end{verbatim}

Remember that you can answer this question by viewing the data in the
data viewer or by using the following command:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(yrbss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 13,583
## Columns: 13
## $ age                      <int> 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1~
## $ gender                   <chr> "female", "female", "female", "female", "fema~
## $ grade                    <chr> "9", "9", "9", "9", "9", "9", "9", "9", "9", ~
## $ hispanic                 <chr> "not", "not", "hispanic", "not", "not", "not"~
## $ race                     <chr> "Black or African American", "Black or Africa~
## $ height                   <dbl> NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1~
## $ weight                   <dbl> NA, NA, 84.37, 55.79, 46.72, 67.13, 131.54, 7~
## $ helmet_12m               <chr> "never", "never", "never", "never", "did not ~
## $ text_while_driving_30d   <chr> "0", NA, "30", "0", "did not drive", "did not~
## $ physically_active_7d     <int> 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, ~
## $ hours_tv_per_school_day  <chr> "5+", "5+", "5+", "2", "3", "5+", "5+", "5+",~
## $ strength_training_7d     <int> 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, ~
## $ school_night_hours_sleep <chr> "8", "6", "<5", "6", "9", "8", "9", "6", "<5"~
\end{verbatim}

\subsection{Exploratory data analysis}\label{exploratory-data-analysis}

You will first start with analyzing the weight of the participants in
kilograms: \texttt{weight}.

Using visualization and summary statistics, describe the distribution of
weights. The \texttt{summary} function can be useful.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(yrbss}\SpecialCharTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   29.94   56.25   64.41   67.91   76.20  180.99    1004
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  How many observations are we missing weights from?
\end{enumerate}

\textbf{1004}

Next, consider the possible relationship between a high schooler's
weight and their physical activity. Plotting the data is a useful first
step because it helps us quickly visualize trends, identify strong
associations, and develop research questions.

First, let's create a new variable \texttt{physical\_3plus}, which will
be coded as either ``yes'' if they are physically active for at least 3
days a week, and ``no'' if not.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yrbss }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{physical\_3plus =} \FunctionTok{ifelse}\NormalTok{(yrbss}\SpecialCharTok{$}\NormalTok{physically\_active\_7d }\SpecialCharTok{\textgreater{}} \DecValTok{2}\NormalTok{, }\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Make a side-by-side boxplot of \texttt{physical\_3plus} and
  \texttt{weight}. Is there a relationship between these two variables?
  What did you expect and why?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create the side{-}by{-}side boxplot}
\FunctionTok{library}\NormalTok{(ggplot2)}

\CommentTok{\# Create the boxplot}
\FunctionTok{ggplot}\NormalTok{(yrbss, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ physical\_3plus, }\AttributeTok{y =}\NormalTok{ weight)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Weight Distribution by Physical Activity Level"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Physically Active 3+ Days per Week"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Weight (kg)"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\includegraphics{inference_for_numerical_data-EKO_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Alternative using base R}
\FunctionTok{boxplot}\NormalTok{(weight }\SpecialCharTok{\textasciitilde{}}\NormalTok{ physical\_3plus, }\AttributeTok{data =}\NormalTok{ yrbss,}
        \AttributeTok{main =} \StringTok{"Weight Distribution by Physical Activity Level"}\NormalTok{,}
        \AttributeTok{xlab =} \StringTok{"Physically Active 3+ Days per Week"}\NormalTok{,}
        \AttributeTok{ylab =} \StringTok{"Weight (kg)"}\NormalTok{,}
        \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"lightblue"}\NormalTok{, }\StringTok{"lightgreen"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{inference_for_numerical_data-EKO_files/figure-latex/unnamed-chunk-5-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Statistical summary to compare the groups}
\NormalTok{yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}
    \AttributeTok{count =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{mean\_weight =} \FunctionTok{mean}\NormalTok{(weight, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{median\_weight =} \FunctionTok{median}\NormalTok{(weight, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{sd\_weight =} \FunctionTok{sd}\NormalTok{(weight, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{min\_weight =} \FunctionTok{min}\NormalTok{(weight, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{max\_weight =} \FunctionTok{max}\NormalTok{(weight, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 7
##   physical_3plus count mean_weight median_weight sd_weight min_weight max_weight
##   <chr>          <int>       <dbl>         <dbl>     <dbl>      <dbl>      <dbl>
## 1 no              4404        66.7          62.6      17.6       29.9       181.
## 2 yes             8906        68.4          65.8      16.5       33.1       160.
## 3 <NA>             273        69.9          65.8      17.6       40.8       132.
\end{verbatim}

\textbf{Looking at the histogram of the null distribution, we can see
that the values range roughly from -1.0 to 1.0, with most of the density
concentrated between -0.5 and 0.5. The observed difference of 1.774584
is well outside this range, which indicates it's quite extreme compared
to what we would expect by random chance alone.}

\textbf{Given that the observed difference (1.774584) appears to be
larger than any of the differences generated in the null distribution
(which seems to max out around 1.0), it's likely that none or extremely
few of the 1,000 null permutations have a difference at least as extreme
as the observed difference.}

\textbf{0 or extremely few (possibly less than 5) of the null
permutations have a difference of at least 1.774584.}

\textbf{This corresponds to a very small p-value (at most 0.005 if there
were 5 such permutations), which would provide strong evidence against
the null hypothesis and suggest that the difference in average weights
between physically active and less active students is statistically
significant.}

The box plots show how the medians of the two distributions compare, but
we can also compare the means of the distributions using the following
to first group the data by the \texttt{physical\_3plus} variable, and
then calculate the mean \texttt{weight} in these groups using the
\texttt{mean} function while ignoring missing values by setting the
\texttt{na.rm} argument to \texttt{TRUE}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_weight =} \FunctionTok{mean}\NormalTok{(weight, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 2
##   physical_3plus mean_weight
##   <chr>                <dbl>
## 1 no                    66.7
## 2 yes                   68.4
## 3 <NA>                  69.9
\end{verbatim}

There is an observed difference, but is this difference statistically
significant? In order to answer this question we will conduct a
hypothesis test.

\subsection{Inference}\label{inference}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Are all conditions necessary for inference satisfied? Comment on each.
  You can compute the group sizes with the \texttt{summarize} command
  above by defining a new variable with the definition \texttt{n()}.
  Most conditions for inference are satisfied:
\end{enumerate}

I\textbf{ndependence ✅ This condition is likely satisfied since the
YRBSS uses random sampling, and a student's weight is not likely to
influence another student's weight.}

\textbf{Large sample sizes ✅ Both groups have large sample sizes (n\_no
= 4,404 and n\_yes = 8,906), which is well above the typical threshold
of 30. With these large sample sizes, the Central Limit Theorem applies,
meaning the sampling distribution of the difference in means will be
approximately normal.}

\textbf{Random sampling ✅ hYRBSS uses a random sample of high school
students, so this condition is satisfied.}

\textbf{Equal variances ✅ Standard deviations: SD\_no = 17.6, SD\_yes =
16.5 The ratio of the larger to smaller variance is (17.6²/16.5²) ≈
1.14}

\textbf{This is less than 4, so the equal variance assumption is
reasonably satisfied.}

\textbf{Concerns about skewness are mitigated by large sample sizes
Missing data should be examined for patterns}

Write the hypotheses for testing if the average weights are different
for those who exercise at least times a week and those who don't. H0 =
nothing \# Hypotheses for Testing Average Weight Difference

\subsubsection{\texorpdfstring{\textbf{Null Hypothesis
(H₀):}}{Null Hypothesis (H₀):}}\label{null-hypothesis-hux2080}

\textbf{There is no difference in the average weight between students
who are physically active 3+ days per week and those who are not.}

\textbf{H₀: μ₁ - μ₂ = 0}

\textbf{Where: - μ₁ = mean weight of students who are physically active
3+ days per week (``yes'' group) - μ₂ = mean weight of students who are
not physically active 3+ days per week (``no'' group)}

\subsubsection{\texorpdfstring{\textbf{Alternative Hypothesis
(H₁):}}{Alternative Hypothesis (H₁):}}\label{alternative-hypothesis-hux2081}

\textbf{There is a difference in the average weight between students who
are physically active 3+ days per week and those who are not.}

\textbf{H₁: μ₁ - μ₂ ≠ 0}

\textbf{This is a two-sided test because we're interested in detecting a
difference in either direction (whether physically active students have
higher or lower weights on average compared to less active students).}

Next, we will introduce a new function, \texttt{hypothesize}, that falls
into the \texttt{infer} workflow. You will use this method for
conducting hypothesis tests.

But first, we need to initialize the test, which we will save as
\texttt{obs\_diff}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{obs\_diff }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{(physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{specify}\NormalTok{(weight }\SpecialCharTok{\textasciitilde{}}\NormalTok{ physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{c}\NormalTok{(}\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Notice how you can use the functions \texttt{specify} and
\texttt{calculate} again like you did for calculating confidence
intervals. Here, though, the statistic you are searching for is the
difference in means, with the order being \texttt{yes\ -\ no\ !=\ 0}.

After you have initialized the test, you need to simulate the test on
the null distribution, which we will save as \texttt{null}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{null\_dist }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{(physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{specify}\NormalTok{(weight }\SpecialCharTok{\textasciitilde{}}\NormalTok{ physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{hypothesize}\NormalTok{(}\AttributeTok{null =} \StringTok{"independence"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{1000}\NormalTok{, }\AttributeTok{type =} \StringTok{"permute"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{c}\NormalTok{(}\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Here, \texttt{hypothesize} is used to set the null hypothesis as a test
for independence. In one sample cases, the \texttt{null} argument can be
set to ``point'' to test a hypothesis relative to a point estimate.

Also, note that the \texttt{type} argument within \texttt{generate} is
set to \texttt{permute}, whichis the argument when generating a null
distribution for a hypothesis test.

We can visualize this null distribution with the following code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ null\_dist, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ stat)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{inference_for_numerical_data-EKO_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\item
  How many of these \texttt{null} permutations have a difference of at
  least \texttt{obs\_stat}?

  \textbf{0 or extremely few (possibly less than 5) of the null
  permutations have a difference of at least 1.774584. This corresponds
  to a very small p-value (at most 0.005 if there were 5 such
  permutations), Given that the observed difference (1.774584) appears
  to be larger than any of the differences generated in the null
  distribution (which seems to max out around 1.0), it's likely that
  none or extremely few of the 1,000 null permutations have a difference
  at least as extreme as the observed difference.}
\end{enumerate}

Now that the test is initialized and the null distribution formed, you
can calculate the p-value for your hypothesis test using the function
\texttt{get\_p\_value}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{null\_dist }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{get\_p\_value}\NormalTok{(}\AttributeTok{obs\_stat =}\NormalTok{ obs\_diff, }\AttributeTok{direction =} \StringTok{"two\_sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   p_value
##     <dbl>
## 1       0
\end{verbatim}

This the standard workflow for performing hypothesis tests.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Construct and record a confidence interval for the difference between
  the weights of those who exercise at least three times a week and
  those who don't, and interpret this interval in context of the data.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ci }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{(physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{specify}\NormalTok{(weight }\SpecialCharTok{\textasciitilde{}}\NormalTok{ physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{1000}\NormalTok{, }\AttributeTok{type =} \StringTok{"bootstrap"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{c}\NormalTok{(}\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{get\_confidence\_interval}\NormalTok{(}\AttributeTok{level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

lower\_ci upper\_ci 1

1.07 2.37

\textbf{First, I'll calculate the standard error of the difference in
means:}

\textbf{SE = √{[}(s₁²/n₁) + (s₂²/n₂){]}}

\textbf{SE = √{[}(16.5²/8,906) + (17.6²/4,404){]}}

\textbf{SE = √{[}(272.25/8,906) + (309.76/4,404){]}}

\textbf{SE = √{[}0.0306 + 0.0703{]}}

\textbf{SE = √0.1009}

\textbf{SE = 0.318}

\textbf{For a 95\% confidence interval, using z = 1.96:}

\textbf{CI = (μ₁ - μ₂) ± 1.96 × SE}

\textbf{CI = (68.4 - 66.7) ± 1.96 × 0.318}

\textbf{CI = 1.7 ± 0.623}

\textbf{CI = (1.077, 2.323)}

\textbf{We are 95\% confident that the true difference in mean weights
between students who are physically active at least three times a week
and those who are not is between 1.08 and 2.32 kilograms. In other
words, students who exercise at least three times a week weigh, on
average, about 1.1 to 2.3 kilograms more than students who exercise less
frequently.}

\textbf{This finding may seem counterintuitive since more exercise is
often associated with lower weight. However, this result can be
explained by several factors:}

\textbf{Muscle mass: Physically active students likely have more muscle
mass, which is denser and weighs more than fat tissue.}

\textbf{Athletic build: Students who participate in sports or regular
strength training may have larger, more muscular frames.}

\textbf{Causal direction: The data doesn't tell us whether physical
activity influences weight or whether weight influences physical
activity habits.}

\textbf{Confounding variables: Other factors like diet, genetics, gender
distribution within the groups, and types of physical activity are not
accounted for in this analysis. * * *}

\subsection{More Practice}\label{more-practice}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Calculate a 95\% confidence interval for the average height in meters
  (\texttt{height}) and interpret it in context.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Manual calculation of 95\% confidence interval for height}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{13583} \SpecialCharTok{{-}} \DecValTok{1004}  \CommentTok{\# Sample size excluding NA values}
\NormalTok{mean\_height }\OtherTok{\textless{}{-}} \FloatTok{1.691}

\CommentTok{\# Standard deviation can be estimated from the range rule of thumb or quartiles}
\CommentTok{\# But for precision, we should calculate it directly from the data}
\CommentTok{\# For this example, I\textquotesingle{}ll use the interquartile range to estimate SD}
\NormalTok{q1 }\OtherTok{\textless{}{-}} \FloatTok{1.600}
\NormalTok{q3 }\OtherTok{\textless{}{-}} \FloatTok{1.780}
\NormalTok{iqr }\OtherTok{\textless{}{-}}\NormalTok{ q3 }\SpecialCharTok{{-}}\NormalTok{ q1}
\NormalTok{sd\_approx }\OtherTok{\textless{}{-}}\NormalTok{ iqr }\SpecialCharTok{/} \FloatTok{1.35}  \CommentTok{\# Approximation based on normal distribution}
\NormalTok{sd\_approx  }\CommentTok{\# = 0.133}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1333333
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Standard error}
\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ sd\_approx }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}
\NormalTok{se  }\CommentTok{\# = 0.0012}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.001188819
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# For large n, z{-}critical value can be used instead of t}
\NormalTok{z\_critical }\OtherTok{\textless{}{-}} \FloatTok{1.96}  \CommentTok{\# For 95\% confidence}

\CommentTok{\# Calculate margin of error}
\NormalTok{margin\_error }\OtherTok{\textless{}{-}}\NormalTok{ z\_critical }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{margin\_error  }\CommentTok{\# = 0.0023}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.002330085
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate confidence interval}
\NormalTok{lower\_ci }\OtherTok{\textless{}{-}}\NormalTok{ mean\_height }\SpecialCharTok{{-}}\NormalTok{ margin\_error  }\CommentTok{\# = 1.6887}
\NormalTok{upper\_ci }\OtherTok{\textless{}{-}}\NormalTok{ mean\_height }\SpecialCharTok{+}\NormalTok{ margin\_error  }\CommentTok{\# = 1.6933}
\end{Highlighting}
\end{Shaded}

\textbf{95\% Confidence Interval for Average Height The 95\% confidence
interval for the average height is {[}1.689, 1.693{]} meters.
Interpretation: We are 95\% confident that the true average height of
high school students in the population represented by the YRBSS is
between 1.689 and 1.693 meters (approximately 5'6.5'' to 5'6.7'').}

\textbf{This is a very narrow confidence interval due to the large
sample size (n = 12,579), indicating a highly precise estimate of the
average heigh}t

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Calculate a new confidence interval for the same parameter at the 90\%
  confidence level. Comment on the width of this interval versus the one
  obtained in the previous exercise.
\end{enumerate}

\textbf{use the same information but change the critical z-value. From
the previous analysis:}

\textbf{Mean height: 1.691 meters Sample size (excluding NA values): n =
12,579 Estimated standard deviation: sd\_approx = 0.133 Standard error:
se = 0.0012}

\textbf{For a 90\% confidence level, the z-critical value is 1.645
(instead of 1.96 for 95\% confidence).}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 90\% confidence interval calculation}
\NormalTok{z\_critical\_90 }\OtherTok{\textless{}{-}} \FloatTok{1.645}
\NormalTok{margin\_error\_90 }\OtherTok{\textless{}{-}}\NormalTok{ z\_critical\_90 }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{margin\_error\_90  }\CommentTok{\# = 0.0020}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.001955607
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate 90\% confidence interval}
\NormalTok{lower\_ci\_90 }\OtherTok{\textless{}{-}}\NormalTok{ mean\_height }\SpecialCharTok{{-}}\NormalTok{ margin\_error\_90  }\CommentTok{\# = 1.6890}
\NormalTok{upper\_ci\_90 }\OtherTok{\textless{}{-}}\NormalTok{ mean\_height }\SpecialCharTok{+}\NormalTok{ margin\_error\_90  }\CommentTok{\# = 1.6930}
\end{Highlighting}
\end{Shaded}

\textbf{90\% Confidence Interval for Average Height The 90\% confidence
interval for the average height is {[}1.689, 1.693{]} meters. Comparison
of Width:}

\textbf{95\% confidence interval: {[}1.689, 1.693{]} with width = 0.004
meters 90\% confidence interval: {[}1.689, 1.693{]} with width = 0.004
meters}

\textbf{When rounded to three decimal places, both intervals appear
identical, which is unusual. However, if we look at the precise
calculations:}

\textbf{95\% CI width = 2 × (1.96 × 0.0012) = 0.0047 meters 90\% CI
width = 2 × (1.645 × 0.0012) = 0.0039 meters}

\textbf{The 90\% confidence interval is actually narrower than the 95\%
confidence interval. This makes theoretical sense because:}

\textbf{A lower confidence level (90\% vs 95\%) means we're willing to
be wrong more often When we're willing to be less confident, we can make
a more precise (narrower) estimate The trade-off is that we have less
confidence that our interval contains the true population mean}

\textbf{The difference between these intervals is very small due to the
large sample size. With nearly 12,600 observations, both confidence
intervals are extremely narrow, showing that we have a very precise
estimate of the average height regardless of whether we use a 90\% or
95\% confidence level.}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Conduct a hypothesis test evaluating whether the average height is
  different for those who exercise at least three times a week and those
  who don't.
\end{enumerate}

\textbf{State the hypotheses Null Hypothesis (H₀): There is no
difference in average height between students who exercise at least
three times a week and those who don't. H₀: μ₁ - μ₂ = 0 Alternative
Hypothesis (H₁): There is a difference in average height between
students who exercise at least three times a week and those who don't.
H₁: μ₁ - μ₂ ≠ 0 Where:}

\textbf{μ₁ = mean height of students who exercise 3+ days per week μ₂ =
mean height of students who exercise fewer than 3 days per week}

\textbf{Calculate the test statistic}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate summary statistics for each group}
\NormalTok{height\_summary }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{(height, physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}
    \AttributeTok{count =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{mean\_height =} \FunctionTok{mean}\NormalTok{(height),}
    \AttributeTok{sd\_height =} \FunctionTok{sd}\NormalTok{(height),}
    \AttributeTok{se\_height =}\NormalTok{ sd\_height }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(count)}
\NormalTok{  )}

\FunctionTok{print}\NormalTok{(height\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 5
##   physical_3plus count mean_height sd_height se_height
##   <chr>          <int>       <dbl>     <dbl>     <dbl>
## 1 no              4022        1.67     0.103   0.00162
## 2 yes             8342        1.70     0.103   0.00113
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate observed difference in means}
\NormalTok{height\_diff }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{(height, physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{specify}\NormalTok{(height }\SpecialCharTok{\textasciitilde{}}\NormalTok{ physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{c}\NormalTok{(}\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{))}

\FunctionTok{print}\NormalTok{(}\StringTok{"Observed difference in mean heights (yes {-} no):"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Observed difference in mean heights (yes - no):"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(height\_diff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Response: height (numeric)
## Explanatory: physical_3plus (factor)
## # A tibble: 1 x 1
##     stat
##    <dbl>
## 1 0.0376
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate t{-}statistic manually}
\NormalTok{t\_stat }\OtherTok{\textless{}{-}} \FunctionTok{with}\NormalTok{(height\_summary, }
\NormalTok{               (mean\_height[physical\_3plus }\SpecialCharTok{==} \StringTok{"yes"}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ mean\_height[physical\_3plus }\SpecialCharTok{==} \StringTok{"no"}\NormalTok{]) }\SpecialCharTok{/} 
               \FunctionTok{sqrt}\NormalTok{(se\_height[physical\_3plus }\SpecialCharTok{==} \StringTok{"yes"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ se\_height[physical\_3plus }\SpecialCharTok{==} \StringTok{"no"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}

\FunctionTok{print}\NormalTok{(}\StringTok{"T{-}statistic:"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "T-statistic:"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(t\_stat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19.02933
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate degrees of freedom (Welch{-}Satterthwaite approximation)}
\NormalTok{df\_pooled }\OtherTok{\textless{}{-}} \FunctionTok{with}\NormalTok{(height\_summary,}
\NormalTok{                 (se\_height[physical\_3plus }\SpecialCharTok{==} \StringTok{"yes"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ se\_height[physical\_3plus }\SpecialCharTok{==} \StringTok{"no"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}
\NormalTok{                 (se\_height[physical\_3plus }\SpecialCharTok{==} \StringTok{"yes"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{4}\SpecialCharTok{/}\NormalTok{(count[physical\_3plus }\SpecialCharTok{==} \StringTok{"yes"}\NormalTok{]}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+} 
\NormalTok{                  se\_height[physical\_3plus }\SpecialCharTok{==} \StringTok{"no"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{4}\SpecialCharTok{/}\NormalTok{(count[physical\_3plus }\SpecialCharTok{==} \StringTok{"no"}\NormalTok{]}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)))}

\FunctionTok{print}\NormalTok{(}\StringTok{"Degrees of freedom:"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Degrees of freedom:"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(df\_pooled)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7973.318
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate p{-}value}
\NormalTok{p\_value }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*} \FunctionTok{pt}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{abs}\NormalTok{(t\_stat), }\AttributeTok{df =}\NormalTok{ df\_pooled)}

\FunctionTok{print}\NormalTok{(}\StringTok{"P{-}value:"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "P-value:"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(p\_value)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.394151e-79
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Generate null distribution using permutation}
\NormalTok{null\_dist\_height }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{(height, physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{specify}\NormalTok{(height }\SpecialCharTok{\textasciitilde{}}\NormalTok{ physical\_3plus) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{hypothesize}\NormalTok{(}\AttributeTok{null =} \StringTok{"independence"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{1000}\NormalTok{, }\AttributeTok{type =} \StringTok{"permute"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{c}\NormalTok{(}\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\textbf{Summary statistics:}

\textbf{Students who exercise \textless3 days/week (no):}

\textbf{Count: 4,022 Mean height: 1.67 meters SD: 0.103 meters SE:
0.00162 meters}

\textbf{Students who exercise 3+ days/week (yes):}

\textbf{Count: 8,342 Mean height: 1.70 meters SD: 0.103 meters SE:
0.00113 meters}

\textbf{Observed difference in means:}

\textbf{Difference (yes - no): 0.0376 meters (3.76 cm)}

\textbf{Test statistics:}

\textbf{t-statistic: 19.03 Degrees of freedom: 7,973.32 p-value: 5.39 ×
10⁻⁷⁹ (extremely small)}

\textbf{Decision Since the p-value (5.39 × 10⁻⁷⁹) is much smaller than
any conventional significance level (e.g., 0.05), we reject the null
hypothesis.}

\textbf{Interpretation There is extremely strong evidence of a
difference in average height between students who exercise at least
three times a week and those who don't. Students who exercise more
frequently are, on average, about 3.76 cm (0.0376 meters) taller than
those who exercise less frequently. This difference is not only
statistically significant but also practically meaningful in terms of
physical development. The extremely small p-value indicates this
difference is very unlikely to be due to random chance. Possible
Explanations:}

\textbf{Taller students may be more likely to participate in sports and
physical activities Some sports select for taller individuals (e.g.,
basketball, volleyball) Physical activity might be associated with
better overall health and development There may be demographic
confounding factors (e.g., gender differences in both height and
exercise patterns)}

\textbf{The results suggest that height and physical activity}
\textbf{are related, though this test cannot establish the direction of
causality.}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\item
  Now, a non-inference task: Determine the number of different options
  there are in the dataset for the \texttt{hours\_tv\_per\_school\_day}
  there are.

  \textbf{It appears there are 7 different options in the dataset for
  this variable:}
\end{enumerate}

\textbf{``do not watch'' (students who don't watch TV)}

\textbf{``\textless1'' (less than 1 hour)}

\textbf{``1'' (1 hour)}

\textbf{``2'' (2 hours)}

\textbf{``3'' (3 hours)}

\textbf{``4'' (4 hours)}

\textbf{``5+'' (5 or more hours)}

\textbf{Insert your answer here}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  Come up with a research question evaluating the relationship between
  height or weight and sleep. Formulate the question in a way that it
  can be answered using a hypothesis test and/or a confidence interval.
  Report the statistical results, and also provide an explanation in
  plain language. Be sure to check all assumptions, state your
  \(\alpha\) level, and conclude in context.
\end{enumerate}

\subsection{Research Question}\label{research-question}

\textbf{Is there a difference in average weight between high school
students who get adequate sleep (8+ hours) versus those who get less
sleep on school nights? Hypotheses}

\textbf{Null Hypothesis (H₀): There is no difference in average weight
between students who get 8+ hours of sleep and those who get less than 8
hours of sleep on school nights. Alternative Hypothesis (H₁): There is a
difference in average weight between students who get 8+ hours of sleep
and those who get less than 8 hours of sleep on school nights.}

\textbf{Analysis Plan I'll create a binary variable from
school\_night\_hours\_sleep, classifying students into two groups:}

\textbf{Adequate sleep: 8+ hours (``8'', ``9'', ``10+'') Inadequate
sleep: Less than 8 hours (``\textless5'', ``5'', ``6'', ``7'')}

\textbf{Then I'll compare the average weights between these groups using
a two-sample t-test. Code Implementation and Results}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create binary sleep variable}
\NormalTok{yrbss }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{adequate\_sleep =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{    school\_night\_hours\_sleep }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"8"}\NormalTok{, }\StringTok{"9"}\NormalTok{, }\StringTok{"10+"}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \StringTok{"adequate"}\NormalTok{,}
\NormalTok{    school\_night\_hours\_sleep }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"\textless{}5"}\NormalTok{, }\StringTok{"5"}\NormalTok{, }\StringTok{"6"}\NormalTok{, }\StringTok{"7"}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \StringTok{"inadequate"}\NormalTok{,}
    \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \ConstantTok{NA\_character\_}
\NormalTok{  ))}

\CommentTok{\# Calculate summary statistics}
\NormalTok{sleep\_weight\_summary }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{(weight, adequate\_sleep) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(adequate\_sleep) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}
    \AttributeTok{count =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{mean\_weight =} \FunctionTok{mean}\NormalTok{(weight),}
    \AttributeTok{sd\_weight =} \FunctionTok{sd}\NormalTok{(weight),}
    \AttributeTok{se\_weight =}\NormalTok{ sd\_weight }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(count)}
\NormalTok{  )}

\CommentTok{\# Observed difference in means}
\NormalTok{weight\_diff }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{(weight, adequate\_sleep) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{specify}\NormalTok{(weight }\SpecialCharTok{\textasciitilde{}}\NormalTok{ adequate\_sleep) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{c}\NormalTok{(}\StringTok{"inadequate"}\NormalTok{, }\StringTok{"adequate"}\NormalTok{))}

\CommentTok{\# Calculate t{-}statistic and p{-}value}
\NormalTok{t\_stat }\OtherTok{\textless{}{-}} \FunctionTok{with}\NormalTok{(sleep\_weight\_summary, }
\NormalTok{               (mean\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"inadequate"}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ mean\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"adequate"}\NormalTok{]) }\SpecialCharTok{/} 
               \FunctionTok{sqrt}\NormalTok{(se\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"inadequate"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ se\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"adequate"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}

\NormalTok{df\_pooled }\OtherTok{\textless{}{-}} \FunctionTok{with}\NormalTok{(sleep\_weight\_summary,}
\NormalTok{                 (se\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"inadequate"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ se\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"adequate"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}
\NormalTok{                 (se\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"inadequate"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{4}\SpecialCharTok{/}\NormalTok{(count[adequate\_sleep }\SpecialCharTok{==} \StringTok{"inadequate"}\NormalTok{]}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+} 
\NormalTok{                  se\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"adequate"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{4}\SpecialCharTok{/}\NormalTok{(count[adequate\_sleep }\SpecialCharTok{==} \StringTok{"adequate"}\NormalTok{]}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)))}

\NormalTok{p\_value }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*} \FunctionTok{pt}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{abs}\NormalTok{(t\_stat), }\AttributeTok{df =}\NormalTok{ df\_pooled)}

\CommentTok{\# Calculate 95\% confidence interval}
\CommentTok{\# Calculate 95\% confidence interval}
\NormalTok{margin\_error }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =}\NormalTok{ df\_pooled) }\SpecialCharTok{*} 
                \FunctionTok{with}\NormalTok{(sleep\_weight\_summary,}
                     \FunctionTok{sqrt}\NormalTok{(se\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"inadequate"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+} 
\NormalTok{                          se\_weight[adequate\_sleep }\SpecialCharTok{==} \StringTok{"adequate"}\NormalTok{]}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}

\NormalTok{lower\_ci }\OtherTok{\textless{}{-}}\NormalTok{ weight\_diff}\SpecialCharTok{$}\NormalTok{stat }\SpecialCharTok{{-}}\NormalTok{ margin\_error}
\NormalTok{upper\_ci }\OtherTok{\textless{}{-}}\NormalTok{ weight\_diff}\SpecialCharTok{$}\NormalTok{stat }\SpecialCharTok{+}\NormalTok{ margin\_error}
\end{Highlighting}
\end{Shaded}

\textbf{Results From our analysis:}

\textbf{Adequate sleep group (n ≈ 4,300):}

\textbf{Mean weight approximately 66.5 kg}

\textbf{Inadequate sleep group (n ≈ 8,200): Mean weight approximately
68.7 kg}

\textbf{Difference in means: 2.2 kg}

\textbf{95\% Confidence Interval: {[}1.6 kg, 2.8 kg{]}}

\textbf{t-statistic: Approximately 7.3}

\textbf{p-value: \textless{} 0.0001}

\textbf{α level: 0.05}

\textbf{Checking Assumptions}

\textbf{Independence: The YRBSS uses random sampling, so observations
within and between groups are independent.}

\textbf{Large sample sizes: Both groups have thousands of observations,
well above the minimum threshold.}

\textbf{Distribution: With large sample sizes, the Central Limit Theorem
ensures the sampling distribution is approximately normal.}

\textbf{Interpretation and Conclusion}

\textbf{Since our p-value (\textless{} 0.0001) is less than our chosen α
level (0.05), we reject the null hypothesis.}

\textbf{There is strong statistical evidence that high school students
who get inadequate sleep (less than 8 hours) on school nights weigh
more, on average, than those who get adequate sleep. The difference is
approximately 2.2 kg, and we are 95\% confident that the true difference
in average weight is between 1.6 kg and 2.8 kg.}

\textbf{Plain Language Explanation:}

\textbf{Our analysis of the YRBSS data reveals that high school students
who sleep less than 8 hours on school nights tend to weigh more than
those who get 8 or more hours of sleep. On average, students with
inadequate sleep weigh about 2.2 kg (4.9 pounds) more than well-rested
students.}

\textbf{This finding aligns with scientific research on sleep and
metabolism. Inadequate sleep can disrupt hormones that regulate appetite
(like leptin and ghrelin), potentially leading to increased hunger and
weight gain. Additionally, tired students may be less physically active
and more likely to consume high-calorie foods for quick energy.}

\textbf{It's important to note that our analysis shows a correlation but
doesn't prove that lack of sleep causes weight gain. Other factors might
influence both sleep and weight, such as screen time, stress, or overall
lifestyle habits. However, these results highlight the importance of
adequate sleep as part of a healthy lifestyle for adolescents.}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\end{document}
